export enum Path {
  HOME = '/',
  USER = 'clients/:id',
  USERS = 'clients',
  CITY = 'cities/:id',
  CITIES = 'cities',
  GOOD = 'product/:id',
  PERSONAL_AREA = 'personal-area',
  GOODS = 'products',
  STOCK = 'promotions/:id',
  STOCKS = 'promotions',
  REVIEW = 'reviews/:id',
  REVIEWS = 'reviews',
  CATEGORY = 'categories/:id',
  CATEGORIES = 'categories',
  PAGE = 'pages/:id',
  PAGES = 'pages',
  AUTH = 'auth',
  REFERRALS = 'referrals',
  ERROR_PAGE = '404',
}
