export enum Options {
  ALL = 'ALL',
  WAIT_FOR_APPROVE = 'WAIT_FOR_APPROVE',
  NOT_APPROVED = 'NOT_APPROVED',
  APPROVED = 'APPROVED',
  ACTUAL = 'ACTUAL',
  PAST = 'PAST',

  MAIN = 'MAIN',
  PURCHASE = 'PURCHASE',
  PRIVACY = 'PRIVACY',
  COOKIE = 'COOKIE',
  AGREEMENT = 'AGREEMENT',
}
